[120] - add the environment in dev workflow

diff --git a/.github/workflows/pre.requisite.yml b/.github/workflows/pre.requisite.yml
--- a/.github/workflows/pre.requisite.yml
+++ b/.github/workflows/pre.requisite.yml
@@ -1,45 +1,45 @@
-name: Create backend
+# name: Create backend
 
-on:
-  workflow_dispatch:
-  push:
-    branches:
-      - main
+# on:
+#   workflow_dispatch:
+#   push:
+#     branches:
+#       - main
 
-jobs:
-  Deploy:
-    runs-on: ubuntu-latest
-    environment: Production
-    defaults:
-      run:
-        working-directory: terraform/pre-requisite
-    env:
-      AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
-      AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
-      AWS_REGION: us-east-1
-    steps:
-      - uses: actions/checkout@v4
-      - uses: hashicorp/setup-terraform@v3
-        with:
-          cli_config_credentials_token: "${{ secrets.TF_API_TOKEN }}"
-      - name: Terraform fmt
-        id: fmt
-        run: terraform fmt -check
-        continue-on-error: true
-      - name: Terraform Init
-        id: init
-        run: terraform init
-      - name: Terraform Validate
-        id: validate
-        run: terraform validate -no-color
-      - name: Terraform Plan
-        id: plan
-        if: github.event_name == 'push'
-        run: terraform plan -no-color -var "BUCKET_NAME=${{ vars.BUCKET_NAME }}" -var "TABLE_NAME=${{ vars.TABLE_NAME }}"
-        continue-on-error: true
-      - name: Terraform Plan Status
-        if: steps.plan.outcome == 'failure'
-        run: exit 1
-      - name: Terraform Apply
-        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
-        run: terraform apply -auto-approve -var "BUCKET_NAME=${{ vars.BUCKET_NAME }}" -var "TABLE_NAME=${{ vars.TABLE_NAME }}"
+# jobs:
+#   Deploy:
+#     runs-on: ubuntu-latest
+#     environment: Production
+#     defaults:
+#       run:
+#         working-directory: terraform/pre-requisite
+#     env:
+#       AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
+#       AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
+#       AWS_REGION: us-east-1
+#     steps:
+#       - uses: actions/checkout@v4
+#       - uses: hashicorp/setup-terraform@v3
+#         with:
+#           cli_config_credentials_token: "${{ secrets.TF_API_TOKEN }}"
+#       - name: Terraform fmt
+#         id: fmt
+#         run: terraform fmt -check
+#         continue-on-error: true
+#       - name: Terraform Init
+#         id: init
+#         run: terraform init
+#       - name: Terraform Validate
+#         id: validate
+#         run: terraform validate -no-color
+#       - name: Terraform Plan
+#         id: plan
+#         if: github.event_name == 'push'
+#         run: terraform plan -no-color -var "BUCKET_NAME=${{ vars.BUCKET_NAME }}" -var "TABLE_NAME=${{ vars.TABLE_NAME }}"
+#         continue-on-error: true
+#       - name: Terraform Plan Status
+#         if: steps.plan.outcome == 'failure'
+#         run: exit 1
+#       - name: Terraform Apply
+#         if: github.ref == 'refs/heads/main' && github.event_name == 'push'
+#         run: terraform apply -auto-approve -var "BUCKET_NAME=${{ vars.BUCKET_NAME }}" -var "TABLE_NAME=${{ vars.TABLE_NAME }}"
